import type { AgentWidgetConfig } from "@runtypelabs/persona";

/** Compact neutral workspace with warm data accents. */
export const aybTheme: NonNullable<AgentWidgetConfig["theme"]> = {
  palette: {
    colors: {
      primary: {
        50: "#f8f9fa",
        100: "#eef0f2",
        200: "#dfe3e7",
        300: "#c9ced4",
        400: "#99a2ad",
        500: "#59636e",
        600: "#414950",
        700: "#343a41",
        800: "#252a30",
        900: "#17181a",
        950: "#0d0e10",
      },
      gray: {
        50: "#f8f9fa",
        100: "#f0f2f4",
        200: "#e1e4e8",
        300: "#c9ced4",
        400: "#99a2ad",
        500: "#737d88",
        600: "#59636e",
        700: "#414950",
        800: "#2a2f35",
        900: "#17181a",
        950: "#0d0e10",
      },
    },
    radius: {
      sm: "6px",
      md: "8px",
      lg: "11px",
      xl: "14px",
      "2xl": "16px",
      full: "9999px",
    },
    shadows: {
      sm: "0 1px 2px rgba(20, 24, 30, 0.05)",
      md: "0 5px 18px rgba(20, 24, 30, 0.07)",
      lg: "0 12px 34px rgba(20, 24, 30, 0.09)",
      xl: "0 18px 48px rgba(20, 24, 30, 0.11)",
      "2xl": "0 24px 64px rgba(20, 24, 30, 0.14)",
    },
    typography: {
      fontFamily: {
        sans: "Inter, 'SF Pro Text', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        mono: "'SFMono-Regular', Consolas, monospace",
      },
      fontSize: {
        xs: "0.6875rem",
        sm: "0.75rem",
        base: "0.8125rem",
        lg: "0.9375rem",
        xl: "1.0625rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "1.875rem",
      },
      lineHeight: {
        tight: "1.2",
        normal: "1.45",
        relaxed: "1.55",
      },
    },
  },
  semantic: {
    colors: {
      primary: "#17181a",
      accent: "#252a30",
      surface: "#ffffff",
      background: "#f5f6f8",
      container: "#f0f2f4",
      text: "#17181a",
      textMuted: "#66707d",
      border: "#e1e4e8",
      divider: "#e8ebee",
      interactive: {
        default: "#17181a",
        hover: "#2a2f35",
        focus: "#414950",
        active: "#0d0e10",
        disabled: "#c9ced4",
      },
    },
    typography: {
      fontFamily: "palette.typography.fontFamily.sans",
      fontSize: "palette.typography.fontSize.base",
      fontWeight: "palette.typography.fontWeight.normal",
      lineHeight: "palette.typography.lineHeight.normal",
    },
  },
  components: {
    button: {
      borderRadius: "9px",
      primary: {
        background: "#17181a",
        foreground: "#ffffff",
        borderRadius: "9px",
        hoverBackground: "#2a2f35",
      },
      secondary: {
        background: "#ffffff",
        foreground: "#252a30",
        border: "#d8dce1",
        borderRadius: "9px",
      },
      ghost: {
        background: "transparent",
        foreground: "#59636e",
        borderRadius: "8px",
        hoverBackground: "#eceef1",
      },
    },
    launcher: { borderRadius: "14px" },
    panel: {
      border: "1px solid #dfe3e7",
      borderRadius: "14px",
      shadow: "0 8px 30px rgba(20, 24, 30, 0.06)",
      inset: "12px",
      canvasBackground: "#f5f6f8",
    },
    header: {
      background: "#f8f9fa",
      border: "#e1e4e8",
      borderRadius: "0",
      titleForeground: "#17181a",
      subtitleForeground: "#737d88",
      actionIconForeground: "#59636e",
      borderBottom: "1px solid #e1e4e8",
      shadow: "none",
    },
    message: {
      user: {
        background: "#eef0f2",
        text: "#202327",
        borderRadius: "12px",
        shadow: "none",
      },
      assistant: {
        background: "transparent",
        text: "#24282d",
        borderRadius: "0",
        border: "transparent",
        shadow: "none",
      },
      border: "#e8ebee",
    },
    introCard: {
      background: "transparent",
      borderRadius: "0",
      padding: "0",
      shadow: "none",
    },
    input: {
      placeholder: "#99a2ad",
      borderRadius: "12px",
      focus: { border: "#aeb5bd", ring: "rgba(23, 24, 26, 0.12)" },
    },
    composer: { shadow: "0 3px 14px rgba(20, 24, 30, 0.06)" },
    toolBubble: { shadow: "none" },
    reasoningBubble: { shadow: "none" },
    collapsibleWidget: {
      container: "#f0f2f4",
      surface: "#ffffff",
      border: "#e1e4e8",
    },
    iconButton: {
      background: "#ffffff",
      border: "1px solid #dfe3e7",
      color: "#59636e",
      padding: "0.4rem",
      borderRadius: "8px",
      hoverBackground: "#f0f2f4",
      hoverColor: "#17181a",
      activeBackground: "#e8ebee",
      activeBorder: "#c9ced4",
    },
    labelButton: {
      background: "#ffffff",
      border: "1px solid #dfe3e7",
      color: "#3b424a",
      padding: "0.45rem 0.7rem",
      borderRadius: "8px",
      hoverBackground: "#f0f2f4",
      fontSize: "0.75rem",
      gap: "0.35rem",
    },
    scrollToBottom: {
      background: "#17181a",
      foreground: "#ffffff",
      border: "#17181a",
      borderRadius: "9999px",
      shadow: "0 3px 12px rgba(20, 24, 30, 0.15)",
    },
    markdown: {
      inlineCode: { background: "#eef0f2", foreground: "#30353b" },
      link: { foreground: "#d95019" },
      prose: {
        fontFamily:
          "Inter, 'SF Pro Text', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      },
      heading: {
        h1: { fontSize: "1.375rem", fontWeight: "740" },
        h2: { fontSize: "1rem", fontWeight: "700" },
      },
      codeBlock: {
        background: "#17191d",
        borderColor: "#2c3036",
        textColor: "#e5e7eb",
      },
      table: { headerBackground: "#f0f2f4", borderColor: "#e1e4e8" },
    },
    artifact: {
      pane: { background: "#f7f8fa", toolbarBackground: "#f8f9fa" },
      toolbar: {
        iconHoverColor: "#17181a",
        iconHoverBackground: "#eceef1",
        iconPadding: "6px",
        iconBorderRadius: "8px",
        iconBorder: "1px solid #dfe3e7",
        iconBackground: "#ffffff",
        toolbarBorder: "1px solid #e1e4e8",
      },
      tab: {
        background: "transparent",
        activeBackground: "#ffffff",
        activeBorder: "#d8dce1",
        borderRadius: "8px",
        textColor: "#66707d",
        hoverBackground: "#eceef1",
        listBackground: "#f0f2f4",
        listBorderColor: "#e1e4e8",
        listPadding: "6px 8px",
      },
      card: {
        background: "#ffffff",
        border: "1px solid #dfe3e7",
        borderRadius: "11px",
        hoverBackground: "#f8f9fa",
        hoverBorderColor: "#c9ced4",
      },
    },
  },
};
